// Language keywords
#define TOKEN_KEYWORDS(_) \
  _(break,       T_BREAK)       \
  _(case,        T_CASE)        \
  _(const,       T_CONST)       \
  _(continue,    T_CONTINUE)    \
  _(default,     T_DEFAULT)     \
  _(defer,       T_DEFER)       \
  _(else,        T_ELSE)        \
  _(enum,        T_ENUM)        \
  _(fallthrough, T_FALLTHROUGH) \
  _(for,         T_FOR)         \
  _(fun,         T_FUN)         \
  _(go,          T_GO)          \
  _(if,          T_IF)          \
  _(import,      T_IMPORT)      \
  _(in,          T_IN)          \
  _(interface,   T_INTERFACE)   \
  _(is,          T_IS)          \
  _(return,      T_RETURN)      \
  _(select,      T_SELECT)      \
  _(struct,      T_STRUCT)      \
  _(switch,      T_SWITCH)      \
  _(symbol,      T_SYMBOL)      \
  _(type,        T_TYPE)        \
  _(var,         T_VAR)         \
  _(while,       T_WHILE)       \
/*END TOKEN_KEYWORDS*/
